# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-14 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorded_jams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordedjam',
            options={'permissions': (('can_download_tracks', 'Can download tracks'), ('can_access_recorded_jams', 'Can access recorded jams'))},
        ),
    ]
