Document: jammr-client
Title: Debian jammr-client Manual
Author: <insert document author here>
Abstract: This manual describes what jammr-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jammr-client/jammr-client.sgml.gz

Format: postscript
Files: /usr/share/doc/jammr-client/jammr-client.ps.gz

Format: text
Files: /usr/share/doc/jammr-client/jammr-client.text.gz

Format: HTML
Index: /usr/share/doc/jammr-client/html/index.html
Files: /usr/share/doc/jammr-client/html/*.html
