# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-15 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stripe_invoice_id',
            field=models.CharField(help_text='Stripe Invoice ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(help_text='Latest Stripe Subscription ID', max_length=255, unique=True),
        ),
    ]
