# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-23 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscription_many_to_one_user_and_on_delete_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='trial_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_plan_id',
            field=models.CharField(help_text='Stripe Plan ID', max_length=255, unique=True),
        ),
    ]
