# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-06 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_trial_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]

