# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_invoice_refunded'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 Country Code', max_length=2)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Tax rate in percent', max_digits=5)),
                ('start_date', models.DateField(help_text='Date when new tax rate comes into effect')),
                ('stripe_taxrate_id', models.CharField(blank=True, help_text='Stripe TaxRate ID', max_length=255)),
            ],
        ),
    ]
