# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-02 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jammr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription',
            field=models.SmallIntegerField(choices=[(0, 'Free'), (1, 'Premium')], default=0),
        ),
    ]
